"""added extension type

Revision ID: 46e65d3fb121
Revises: 6bd3c785b01e
Create Date: 2026-08-16 20:36:51.704518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e65d3fb121'
down_revision: Union[str, Sequence[str], None] = '6bd3c785b01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extension_type', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extension_type')
    # ### end Alembic commands ###
