"""final fix

Revision ID: 6ab07cd73116
Revises: b4fc53cf9aeb
Create Date: 2026-07-27 18:42:04.161357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab07cd73116'
down_revision: Union[str, Sequence[str], None] = 'b4fc53cf9aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_client_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_client_id_fkey'), 'documents', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
