"""add chunk_index and page to document_chunk

Revision ID: 8a68d52118ff
Revises: 1670c3087969
Create Date: 2026-09-05 18:27:26.599059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a68d52118ff'
down_revision: Union[str, Sequence[str], None] = '1670c3087969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.add_column('document_chunks', sa.Column('page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'page')
    op.drop_column('document_chunks', 'chunk_index')
    # ### end Alembic commands ###
