"""fix ondelete CASCADE on created_by_id

Revision ID: b4fc53cf9aeb
Revises: 9d0debaf5eeb
Create Date: 2026-07-27 18:38:47.429946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fc53cf9aeb'
down_revision: Union[str, Sequence[str], None] = '9d0debaf5eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_created_by_id_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_created_by_id_fkey'), 'clients', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###
