"""documents

Revision ID: c06ea83a8156
Revises: 8cf9e646dda5
Create Date: 2026-07-27 17:20:29.614807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06ea83a8156'
down_revision: Union[str, Sequence[str], None] = '8cf9e646dda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file')
    # ### end Alembic commands ###
