"""final fix

Revision ID: d676b99a0b77
Revises: 6ab07cd73116
Create Date: 2026-07-27 18:46:38.337457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd676b99a0b77'
down_revision: Union[str, Sequence[str], None] = '6ab07cd73116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('password_reset_token_user_id_fkey'), 'password_reset_token', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_token', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_token', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_token_user_id_fkey'), 'password_reset_token', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
